### ISSUE TITLE
Neuroscience focus yes|no?

### ISSUE THREAD

**Issue by mih** [datalad/datalad-paper-joss#15]
The present abstract states:

> Born from the idea to provide a unified data distribution for neuroscience

While I believe this is not meant to be a scope-limit, it nevertheless makes the impression to me.

Q: Do we agree that there should *not* be the notion of "datalad is RDM for neuroscience"?

**Comment by yarikoptic** [comment]
Yes

But I think it is ok to state original domain/purpose

**Comment by yarikoptic** [comment]
We ~~can~~ should add explicit statement on fields of science where we know it has been used already: neuroscience, physics, machine learning, bioinformatics ideally with references to example papers or datasets

**Comment by adswa** [comment]
Suggestion:

Instead of 
> The simplest "prototypical" example is datalad search haxby which would install the http://datasets.datalad.org superdataset, and search for datasets mentioning haxby anywhere in their metadata records. Any reported dataset could be immediately installed using datalad install command, and data files of interest obtained using datalad get.


Should we simply refer to the handbook usecases and the asci casts on the datalad website for prototypical examples from a few fields? I think this is @yarikoptic's  simplest prototypical usecase and people that are unfamiliar with Haxby or the data he has published will be confused :P It also puts a bit of a focus on ``datalad search``, which is not even documented in the handbook and may backfire if anyone want to read up on this "prototypical example"

**Comment by yarikoptic** [comment]
I think we should have some specific example in the manuscript to not only address reviewer checklist item

    Example usage: Do the authors include examples of how to use the software
    (ideally to solve real-world analysis problems).

but also to give some "ready to use" command any reader could try right away without going anywhere else. And then we definitely should add a reference to the handbook.

> ... people that are unfamiliar with Haxby or the data he has published ...

We could clarify : 

   The simplest "prototypical" example is datalad search haxby which would install the http://datasets.datalad.org superdataset, and search for datasets mentioning haxby --a prominent neuroscientist who supported and facilitated DataLad birth-- anywhere in their metadata records.

In either case we should also add Jim to acknowledgement section: https://github.com/datalad/datalad-paper-joss/pull/17

> It also puts a bit of a focus on datalad search, which is not even documented in the handbook and may backfire if anyone want to read up on this "prototypical example"

Well, I think it is a shortcoming of the handbook, should be addressed there (https://github.com/datalad-handbook/book/issues/324 and I am not even an author), and although can contribute to decision making of replacing `datalad search` with some other exemplar command here, should not be the only factor.  Meanwhile we can add a reference to http://docs.datalad.org/en/stable/generated/man/datalad-search.html to accompany that example command, which might be of benefit as well since we do not link much into docs.datalad.org.

**Comment by yarikoptic** [comment]
> Should we simply refer to the handbook usecases and the asci casts on the datalad website for prototypical examples from a few fields?

We should definitely point to handbook usecases, will send a PR now.  ascinema casts on website -- nah, should be gone, apparently there is no issue so filed a new one https://github.com/datalad/datalad.org/issues/75

**Comment by yarikoptic** [comment]
agreement for focus was "No". Unfortunately there is not that many examples of use to demonstrate for other fields ATM though.
